name: build
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.md'
      - '*.md'
      - 'docs/**'
      - 'kube/**'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.md'
      - '*.md'
      - 'docs/**'
      - 'kube/**'
      - 'LICENSE'
      - 'NOTICE'
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vendor Go modules
        run: go mod vendor
      - name: Verify generated code
        run: GOPATH="$(go env GOPATH)" ./hack/verify-codegen.sh
      - name: Run unit tests
        run: make unit-tests
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
      - name: Setup Kubernetes cluster (KIND)
        uses: engineerd/setup-kind@v0.4.0
      - name: Test connection to Kubernetes cluster
        run: |
          kubectl cluster-info
      - name: Run integration tests
        run: |
          make integration-tests
          ./bin/starboard init -v 3
          kubectl get crd
        env:
          KUBECONFIG: /home/runner/.kube/config
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.138.0
          args: release --snapshot --skip-publish --rm-dist
